### This file is automatically generated.
### See [conditions]/inst/autogen/autogen.R.

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
assertion_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "assertion", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
io_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "io", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
length_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "length", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
library_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "library", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
lookup_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "lookup", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
missing_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "missing", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
name_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "name", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
runtime_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "runtime", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
type_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "type", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_error_
#' @export
value_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "value", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
assertion_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "assertion", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
io_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "io", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
length_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "length", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
library_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "library", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
lookup_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "lookup", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
missing_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "missing", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
name_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "name", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
runtime_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "runtime", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
type_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "type", message, call)
}

#' @rdname std_conditions
#' @useDynLib conditions condition_warning_
#' @export
value_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "value", message, call)
}

