### This file is automatically generated.
### See [conditions]/inst/autogen/autogen.R.


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
assertion_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "assertion", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_assertion_message = function(message = NULL) {
  as_message("assertion", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
deprecated_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "deprecated", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_deprecated_message = function(message = NULL) {
  as_message("deprecated", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
dimension_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "dimension", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_dimension_message = function(message = NULL) {
  as_message("dimension", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
future_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "future", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_future_message = function(message = NULL) {
  as_message("future", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
index_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "index", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_index_message = function(message = NULL) {
  as_message("index", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
io_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "io", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_io_message = function(message = NULL) {
  as_message("io", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
length_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "length", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_length_message = function(message = NULL) {
  as_message("length", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
library_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "library", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_library_message = function(message = NULL) {
  as_message("library", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
lookup_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "lookup", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_lookup_message = function(message = NULL) {
  as_message("lookup", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
missing_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "missing", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_missing_message = function(message = NULL) {
  as_message("missing", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
name_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "name", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_name_message = function(message = NULL) {
  as_message("name", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
runtime_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "runtime", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_runtime_message = function(message = NULL) {
  as_message("runtime", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
type_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "type", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_type_message = function(message = NULL) {
  as_message("type", message)
}


#' @rdname condition
#' @useDynLib conditions condition_message_
#' @export
value_message = function(message, call = sys.call(-1L)) {
  .Call(condition_message_, "value", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_message_
#' @export
as_value_message = function(message = NULL) {
  as_message("value", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
assertion_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "assertion", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_assertion_warning = function(message = NULL) {
  as_warning("assertion", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
deprecated_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "deprecated", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_deprecated_warning = function(message = NULL) {
  as_warning("deprecated", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
dimension_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "dimension", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_dimension_warning = function(message = NULL) {
  as_warning("dimension", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
future_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "future", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_future_warning = function(message = NULL) {
  as_warning("future", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
index_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "index", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_index_warning = function(message = NULL) {
  as_warning("index", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
io_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "io", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_io_warning = function(message = NULL) {
  as_warning("io", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
length_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "length", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_length_warning = function(message = NULL) {
  as_warning("length", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
library_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "library", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_library_warning = function(message = NULL) {
  as_warning("library", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
lookup_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "lookup", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_lookup_warning = function(message = NULL) {
  as_warning("lookup", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
missing_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "missing", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_missing_warning = function(message = NULL) {
  as_warning("missing", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
name_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "name", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_name_warning = function(message = NULL) {
  as_warning("name", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
runtime_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "runtime", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_runtime_warning = function(message = NULL) {
  as_warning("runtime", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
type_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "type", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_type_warning = function(message = NULL) {
  as_warning("type", message)
}


#' @rdname condition
#' @useDynLib conditions condition_warning_
#' @export
value_warning = function(message, call = sys.call(-1L)) {
  .Call(condition_warning_, "value", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_warning_
#' @export
as_value_warning = function(message = NULL) {
  as_warning("value", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
assertion_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "assertion", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_assertion_error = function(message = NULL) {
  as_error("assertion", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
deprecated_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "deprecated", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_deprecated_error = function(message = NULL) {
  as_error("deprecated", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
dimension_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "dimension", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_dimension_error = function(message = NULL) {
  as_error("dimension", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
future_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "future", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_future_error = function(message = NULL) {
  as_error("future", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
index_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "index", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_index_error = function(message = NULL) {
  as_error("index", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
io_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "io", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_io_error = function(message = NULL) {
  as_error("io", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
length_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "length", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_length_error = function(message = NULL) {
  as_error("length", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
library_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "library", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_library_error = function(message = NULL) {
  as_error("library", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
lookup_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "lookup", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_lookup_error = function(message = NULL) {
  as_error("lookup", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
missing_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "missing", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_missing_error = function(message = NULL) {
  as_error("missing", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
name_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "name", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_name_error = function(message = NULL) {
  as_error("name", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
runtime_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "runtime", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_runtime_error = function(message = NULL) {
  as_error("runtime", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
type_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "type", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_type_error = function(message = NULL) {
  as_error("type", message)
}


#' @rdname condition
#' @useDynLib conditions condition_error_
#' @export
value_error = function(message, call = sys.call(-1L)) {
  .Call(condition_error_, "value", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_error_
#' @export
as_value_error = function(message = NULL) {
  as_error("value", message)
}
