conditions = c(
  "assertion",
  "deprecated",
  "dimension",
  "future",
  "index",
  "io",
  "length",
  "library",
  "lookup",
  "missing",
  "name",
  "runtime",
  "type",
  "value"
)

template = ("
#' @rdname condition
#' @useDynLib conditions condition_%1$s_
#' @export
%2$s_%1$s = function(message, call = sys.call(-1L)) {
  .Call(condition_%1$s_, \"%2$s\", message, call)
}

#' @rdname as_condition
#' @useDynLib conditions condition_%1$s_
#' @export
as_%2$s_%1$s = function(message = NULL) {
  as_%1$s(\"%2$s\", message)
}
")

lines = character(0L)
con = textConnection("lines", open = "wt")
cat("### This file is automatically generated.", "### See [conditions]/inst/autogen/autogen.R.", "", sep = "\n", file = con)
for (type in c("message", "warning", "error")) {
  for (cond in conditions) {
    cat(sprintf(template, type, cond), "\n", sep = "", file = con)
  }
}
close(con)

path = devtools::as.package(".")$path
writeLines(head(lines, -1), file.path(path, "R", "autogenerated.R"))
